name: test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v6.3.0
        with:
          cache: false
          go-version: '1.21'
      - uses: actions/checkout@v6.0.2
      - uses: n8maninger/action-golang-test@v2.1.1
        with:
          args: "-race;-timeout=30m"

